flags: {}
resolver: lts-10.10
packages:
- location: .
- location:
    git: git@github.com:timbod7/adl.git
    commit: 0.9.4
  subdirs:
  - haskell/utils
  - haskell/runtime
  - haskell/compiler-lib
  - haskell/compiler
  extra-dep: true
