name: Build and test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('haskell/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build core adl and run tests
        run: "cd haskell && stack build --fast adl-compiler && stack test --fast --no-terminal adl-compiler"

      - name: Build hx-adl haskell
        run: "cd haskell && stack build --fast helix-adl-tools"

      - name: Build hx-adl typescript
        run: "cd typescript/hx-adl && rm -rf build && yarn && yarn build"
