name: Build and test
on:
  pull_request:
  push:
    branches:
      - ci-dev
      - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]

    steps:      
      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Fetch all history so git describe works
      - run: |
          git fetch --prune --unshallow

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Cache haskell dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-${{ hashFiles('haskell/stack.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-

      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            doit
            pystache

      - name: Build core adl and run tests
        run: "cd haskell && stack build --fast adl-compiler && stack test --fast --no-terminal adl-compiler"

      - name: Build hx-adl haskell
        run: "cd haskell && stack build --fast helix-adl-tools"

      - name: Build hx-adl typescript
        run: "cd typescript/hx-adl && rm -rf build && yarn && yarn build"

      - name: Test Release Build
        run: "doit build_release"
